config/routes.rb
Rails.application.routes.draw do
  resources :contracts
  root 'contracts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_params
      params.require(:contract).permit(:name, :cnpj, :local, :nameRep, :nac, :status, :prof, :CPF, :RG, :end 
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
    require 'docx'


    def loaddocx
        
        # Create a Docx::Document object for our existing docx file
        doc = Docx::Document.open('./public/modelo.docx')
        cont = 1
        # puts doc
        # Retrieve and display paragraphs
        doc.paragraphs.each do |p|
          # puts p.class
            p.each_text_run do |tr|
              substituteText = "<ac-"+ cont.to_s + ">"
              if tr.to_s == substituteText
                
                tr.substitute(substituteText.to_s, "SUBSTITUTE SUCCESS")
                puts cont+=1
              end 
            end
            
            
        end 
         doc.paragraphs.each do |p|
           puts p 
        end 
        
        # doc.bookmarks do |bookmark_o|
        #   puts bookmark_name
        # end

        # doc.save('./public/new.doc')
    end
end

app/views/contracts/_form.html.erb
		<div class="login-form">
<%= form_with(model: contract, local: true) do |form| %>
  <% if contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  	<div class="sign-up-htm">


		<div class="group"> 
    <%= form.label :Nome_da_Empresa ,for:"user", class:"label"%>
    <%= form.text_field :name ,id:"user",class:"input"%>
				
					
				</div>



  

  <div class="group">
    <%= form.label :CNPJ,for:"user", class:"label" %>
    <%= form.text_field :cnpj,id:"user",class:"input" %>
  </div>
  <div class="group">
    <%= form.label :Endereço_da_Empresa,for:"user", class:"label" %>
    <%= form.text_field :local,id:"user",class:"input" %>
  </div>
  <div class="group">
    <%= form.label :Nome_do_representante,for:"user", class:"label" %>
    <%= form.text_field :nameRep,id:"user",class:"input" %>
  </div>

<div class="group">
    <%= form.label :Nacionalidade,for:"user", class:"label" %>
    <%= form.text_field :nac,id:"user",class:"input" %>
  </div>

<div class="group">
    <%= form.label :Estado_Civil,for:"user", class:"label" %>
    <%= form.text_field :status,id:"user",class:"input" %>
  </div>
  <div class="group">
    <%= form.label :'Profissão',for:"user", class:"label" %>
    <%= form.text_field :prof,id:"user",class:"input" %>
  </div>

 <div class="group">
    <%= form.label :'CPF',for:"user", class:"label" %>
    <%= form.text_field :CPF,id:"user",class:"input" %>
  </div>

 <div class="group">
    <%= form.label :'RG',for:"user", class:"label" %>
    <%= form.text_field :RG,id:"user",class:"input" %>
  </div>
  <div class="group">
    <%= form.label :'Endereço do Representante',for:"user", class:"label" %>
    <%= form.text_field :end,id:"user",class:"input" %>
  </div>




   

  <div class="group">
    <%= form.submit "",class:"button" ,value:"Salvar"%>
  </div>
  </div>
<% end %>
		</div>
	

		<!--				<div class="group">
					<label for="user" class="label">Username</label>
					<input id="user" type="text" class="input">
				</div>
				<div class="group">
					<label for="pass" class="label">Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<label for="pass" class="label">Repeat Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<label for="pass" class="label">Email Address</label>
					<input id="pass" type="text" class="input">
				</div>-->

			
			

app/views/contracts/edit.html.erb
<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-up" checked><label for="tab-2" class="tab">Novo contrato</label>

<%= render 'form', contract: @contract %>
<div class="hr"></div>
<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>
</div>
</div>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contratos</h1>
<%loaddocx%>
<table>
  <thead>
    <tr>
      <th>Empresa</th>
      <th>CNPJ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.name %></td>
        <td><%= contract.cnpj %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-up" checked><label for="tab-2" class="tab">Novo contrato</label>
<%= render 'form', contract: @contract %>
	
</div>

<% link_to 'Back' ,contracts_path,class:"button" %>
</div>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @contract.name %>
</p>

<p>
  <strong>CNPJ:</strong>
  <%= @contract.cnpj %>
</p>

<%= link_to 'Editar', edit_contract_path(@contract) %> |
<%= link_to 'Voltar', contracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contrato</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>